#[cfg(test)]
use chrono::{TimeZone, Utc};
#[cfg(test)]
use crate::contracts::RecommendationCandidatePayload;

#[cfg(test)]
pub fn make_test_candidate(post_id: &str, author_id: &str) -> RecommendationCandidatePayload {
    RecommendationCandidatePayload {
        post_id: post_id.to_string(),
        model_post_id: Some(post_id.to_string()),
        author_id: author_id.to_string(),
        content: "test content".to_string(),
        created_at: Utc.with_ymd_and_hms(2026, 4, 20, 0, 0, 0).unwrap(),
        conversation_id: None,
        is_reply: false,
        reply_to_post_id: None,
        is_repost: false,
        original_post_id: None,
        in_network: None,
        recall_source: None,
        retrieval_lane: None,
        interest_pool_kind: None,
        topic_ids: Vec::new(),
        secondary_recall_sources: None,
        has_video: None,
        has_image: None,
        video_duration_sec: None,
        has_media: false,
        media_type: crate::contracts::MediaType::None,
        video_duration_ms: None,
        media: None,
        like_count: None,
        comment_count: None,
        repost_count: None,
        view_count: None,
        author_username: None,
        author_avatar_url: None,
        author_affinity_score: None,
        author_blocks_viewer: None,
        language_code: None,
        phoenix_scores: None,
        action_scores: None,
        ranking_signals: None,
        recall_evidence: None,
        selection_pool: None,
        selection_reason: None,
        score_contract_version: None,
        score_breakdown_version: None,
        weighted_score: None,
        score: None,
        pipeline_score: None,
        score_breakdown: None,
        is_liked_by_user: None,
        is_reposted_by_user: None,
        is_nsfw: None,
        vf_result: None,
        is_news: None,
        news_metadata: None,
        is_pinned: None,
        is_subscription_only: None,
        graph_score: None,
        graph_path: None,
        graph_recall_type: None,
        post_type: None,
        mutual_follow_jaccard: None,
        following_replied: None,
    }
}
