use serde::{Deserialize, Serialize};
use std::collections::HashMap;

use super::pipeline::RecommendationOnlineEvaluationPayload;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct StageLatencySnapshot {
    pub last_ms: u64,
    pub p50_ms: u64,
    pub p95_ms: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RecommendationSourceHealthEntry {
    pub source: String,
    pub enabled: bool,
    pub output_count: usize,
    pub duration_ms: u64,
    pub timed_out: bool,
    pub degraded: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error_class: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub disabled_reason: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source_budget: Option<usize>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pre_policy_count: Option<usize>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RecommendationGuardrailStatus {
    pub status: String,
    pub empty_retrieval: bool,
    pub empty_selection: bool,
    pub underfilled_selection: bool,
    pub ml_ranking_empty: bool,
    pub provider_budget_exceeded: bool,
    pub source_timeout_count: usize,
    pub source_error_count: usize,
    pub degraded_reason_count: usize,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RecommendationOpsRuntime {
    pub stage: String,
    pub backend_url: String,
    pub redis_url: String,
    pub retrieval_mode: String,
    pub ranking_mode: String,
    pub serving_version: String,
    pub cursor_mode: String,
    pub stage_execution_mode: String,
    pub runtime_contract_version: String,
    pub component_order_hash: String,
    pub query_hydrator_execution_mode: String,
    pub source_execution_mode: String,
    pub candidate_hydrator_execution_mode: String,
    pub post_selection_hydrator_execution_mode: String,
    pub query_hydrator_transport_mode: String,
    pub source_transport_mode: String,
    pub candidate_hydrator_transport_mode: String,
    pub post_selection_hydrator_transport_mode: String,
    pub provider_latency_mode: String,
    pub graph_materializer_cache_mode: String,
    pub source_policy_mode: String,
    pub guardrail_mode: String,
    pub provider_latency_budget_ms: u64,
    pub source_batch_component_timeout_ms: u64,
    pub query_hydrator_concurrency: usize,
    pub source_concurrency: usize,
    pub candidate_hydrator_concurrency: usize,
    pub post_selection_hydrator_concurrency: usize,
    pub pipeline_version: String,
    pub owner: String,
    pub fallback_mode: String,
    pub graph_provider_mode: String,
    pub graph_kernel_url: String,
    pub query_hydrators: Vec<String>,
    pub source_order: Vec<String>,
    pub candidate_hydrators: Vec<String>,
    pub filters: Vec<String>,
    pub scorers: Vec<String>,
    pub selectors: Vec<String>,
    pub post_selection_hydrators: Vec<String>,
    pub post_selection_filters: Vec<String>,
    pub side_effects: Vec<String>,
    pub graph_source_enabled: bool,
    pub graph_materializer_limit_per_author: usize,
    pub graph_materializer_lookback_days: usize,
    pub recent_global_capacity: usize,
    pub recent_per_user_capacity: usize,
    pub selector_oversample_factor: usize,
    pub selector_max_size: usize,
    pub serve_cache_enabled: bool,
    pub serve_cache_ttl_secs: usize,
    pub serve_cache_prefix: String,
    pub serve_cache_key_mode: String,
    pub serve_cache_policy_mode: String,
    pub async_side_effect_mode: String,
    pub pipeline_stage_manifest: Vec<RecommendationPipelineStageManifestEntry>,
    pub serving_author_soft_cap: usize,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RecommendationPipelineStageManifestEntry {
    pub stage: String,
    pub component: String,
    pub owner: String,
    pub execution_mode: String,
    pub transport_mode: String,
    pub fallback_behavior: String,
    pub criticality: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RecentStoreSnapshot {
    pub global_size: usize,
    pub tracked_users: usize,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RecommendationOpsSummary {
    pub status: String,
    pub current_stage: String,
    pub total_requests: u64,
    pub total_failures: u64,
    pub last_request_id: Option<String>,
    pub last_selected_count: Option<usize>,
    pub last_retrieved_count: Option<usize>,
    pub last_has_more: Option<bool>,
    pub last_next_cursor: Option<String>,
    pub last_serving_version: Option<String>,
    pub last_cursor_mode: Option<String>,
    pub last_served_state_version: Option<String>,
    pub last_stable_order_key: Option<String>,
    pub last_duplicate_suppressed_count: Option<usize>,
    pub last_cross_page_duplicate_count: Option<usize>,
    pub last_serve_cache_hit: Option<bool>,
    pub serve_cache_hit_rate: Option<f64>,
    pub last_cache_policy_reason: Option<String>,
    pub last_page_remaining_count: Option<usize>,
    pub last_page_underfilled: Option<bool>,
    pub last_page_underfill_reason: Option<String>,
    pub last_suppression_reasons: HashMap<String, usize>,
    pub serve_cache_hit_count: u64,
    pub serve_cache_miss_count: u64,
    pub stable_order_drift_count: u64,
    pub page_underfill_count: u64,
    pub page_underfill_rate: Option<f64>,
    pub suppression_reason_counts: HashMap<String, u64>,
    pub underfill_reason_counts: HashMap<String, u64>,
    pub last_rescue_selected_count: Option<usize>,
    pub self_post_rescue_attempt_count: u64,
    pub self_post_rescue_hit_count: u64,
    pub self_post_rescue_hit_rate: Option<f64>,
    pub last_ml_retrieved_count: Option<usize>,
    pub last_ml_ranked_count: Option<usize>,
    pub last_graph_retrieved_count: Option<usize>,
    pub last_graph_kernel_candidates: Option<usize>,
    pub last_graph_legacy_candidates: Option<usize>,
    pub last_graph_fallback_used: Option<bool>,
    pub last_graph_materializer_query_duration_ms: Option<u64>,
    pub last_graph_materializer_provider_latency_ms: Option<u64>,
    pub last_graph_materializer_cache_hit: Option<bool>,
    pub graph_materializer_cache_hit_count: u64,
    pub graph_materializer_cache_miss_count: u64,
    pub graph_materializer_cache_hit_rate: Option<f64>,
    pub last_graph_materializer_cache_key_mode: Option<String>,
    pub last_graph_materializer_cache_ttl_ms: Option<u64>,
    pub last_graph_materializer_cache_entry_count: Option<usize>,
    pub last_graph_materializer_cache_eviction_count: Option<u64>,
    pub last_graph_kernel_source_counts: HashMap<String, usize>,
    pub last_graph_per_kernel_candidate_counts: HashMap<String, usize>,
    pub last_graph_per_kernel_requested_limits: HashMap<String, usize>,
    pub last_graph_per_kernel_available_counts: HashMap<String, usize>,
    pub last_graph_per_kernel_returned_counts: HashMap<String, usize>,
    pub last_graph_per_kernel_truncated_counts: HashMap<String, usize>,
    pub last_graph_per_kernel_latency_ms: HashMap<String, u64>,
    pub last_graph_per_kernel_empty_reasons: HashMap<String, String>,
    pub last_graph_per_kernel_errors: HashMap<String, String>,
    pub last_graph_budget_exhausted_kernels: Vec<String>,
    pub last_graph_dominant_source: Option<String>,
    pub last_graph_dominance_share: Option<f64>,
    pub last_graph_empty_reason: Option<String>,
    pub last_provider_calls: HashMap<String, usize>,
    pub last_provider_latency_ms: HashMap<String, u64>,
    pub last_slow_provider: Option<String>,
    pub last_slow_provider_ms: Option<u64>,
    pub provider_latency_budget_exceeded_count: u64,
    pub provider_latency_budget_ms: u64,
    pub source_batch_timeout_count: u64,
    pub last_source_batch_timed_out_sources: Vec<String>,
    pub source_batch_component_timeout_ms: u64,
    pub last_source_health: Vec<RecommendationSourceHealthEntry>,
    pub guardrails: RecommendationGuardrailStatus,
    pub empty_retrieval_count: u64,
    pub empty_selection_count: u64,
    pub underfilled_selection_count: u64,
    pub phoenix_empty_ranking_count: u64,
    pub last_online_eval: RecommendationOnlineEvaluationPayload,
    pub online_eval_total_selected: u64,
    pub online_eval_trend_selected: u64,
    pub online_eval_news_selected: u64,
    pub online_eval_exploration_selected: u64,
    pub online_eval_source_counts: HashMap<String, u64>,
    pub online_eval_lane_counts: HashMap<String, u64>,
    pub online_eval_pool_counts: HashMap<String, u64>,
    pub stage_latency: HashMap<String, StageLatencySnapshot>,
    pub partial_degrade_count: u64,
    pub timeout_count: u64,
    pub side_effect_dispatch_count: u64,
    pub side_effect_complete_count: u64,
    pub side_effect_failure_count: u64,
    pub last_side_effect_error: Option<String>,
    pub last_side_effect_names: Vec<String>,
    pub last_side_effect_completed_at: Option<String>,
    pub degraded_reasons: Vec<String>,
    pub recent_store: RecentStoreSnapshot,
}
