"""Add missing fields

Revision ID: f6b3b6d74085
Revises: 
Create Date: 2025-07-25 15:44:57.739517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6b3b6d74085'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_name'), ['name'], unique=True)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comment_approved'), ['approved'], unique=False)
        batch_op.create_index('ix_comment_approved_timestamp', ['approved', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index('ix_comment_post_approved', ['post_id', 'approved'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_comment_user_timestamp', ['user_id', 'timestamp'], unique=False)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keywords', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('featured', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reading_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('published_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('featured_image',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_post_timestamp'))
        batch_op.create_index('ix_post_category_published', ['category_id', 'published'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_published'), ['published'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_published_at'), ['published_at'], unique=False)
        batch_op.create_index('ix_post_published_timestamp', ['published', 'published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_title'), ['title'], unique=False)
        batch_op.create_index('ix_post_user_published', ['user_id', 'published'], unique=False)
        batch_op.create_index('ix_post_views_published', ['views', 'published'], unique=False)
        batch_op.drop_column('likes')
        batch_op.drop_column('last_modified')
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_name'), ['name'], unique=True)

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tag_name'), ['name'], unique=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_confirmed'), ['confirmed'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_is_admin'), ['is_admin'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_last_seen'), ['last_seen'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_member_since'), ['member_since'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_member_since'))
        batch_op.drop_index(batch_op.f('ix_user_last_seen'))
        batch_op.drop_index(batch_op.f('ix_user_is_admin'))
        batch_op.drop_index(batch_op.f('ix_user_confirmed'))

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tag_name'))

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_name'))

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('last_modified', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('likes', sa.INTEGER(), nullable=True))
        batch_op.drop_index('ix_post_views_published')
        batch_op.drop_index('ix_post_user_published')
        batch_op.drop_index(batch_op.f('ix_post_title'))
        batch_op.drop_index('ix_post_published_timestamp')
        batch_op.drop_index(batch_op.f('ix_post_published_at'))
        batch_op.drop_index(batch_op.f('ix_post_published'))
        batch_op.drop_index(batch_op.f('ix_post_created_at'))
        batch_op.drop_index('ix_post_category_published')
        batch_op.create_index(batch_op.f('ix_post_timestamp'), ['timestamp'], unique=False)
        batch_op.alter_column('featured_image',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('published_at')
        batch_op.drop_column('reading_time')
        batch_op.drop_column('featured')
        batch_op.drop_column('status')
        batch_op.drop_column('keywords')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_index('ix_comment_user_timestamp')
        batch_op.drop_index(batch_op.f('ix_comment_user_id'))
        batch_op.drop_index(batch_op.f('ix_comment_post_id'))
        batch_op.drop_index('ix_comment_post_approved')
        batch_op.drop_index(batch_op.f('ix_comment_parent_id'))
        batch_op.drop_index('ix_comment_approved_timestamp')
        batch_op.drop_index(batch_op.f('ix_comment_approved'))

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_name'))

    # ### end Alembic commands ###
